service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

enabled: false
image: ""
loggingLevelRoot: "INFO"
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "256M"

ingress:
  enabled: false
  annotations: {}
  pathtype: ImplementationSpecific
  hosts:
    - host: ""
      paths:
        - path: /
  tls: []

deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 30

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 30
