ams:
  local:
    interop:
      host: https://rhino.mifos.io:8443
    customer:
      host: https://rhino.mifos.io:8443
    account:
      host: https://rhino.mifos.io:8443
    auth:
      host: https://rhino.mifos.io:8443
    tenants:
      - name: "gorilla"
        user: mifos
        password: password
        authtype: basic
        fspId: payerfsp
      - name: "wakanda"
        user: mifos
        password: password
        authtype: basic
        fspId: payerfsp
      - name: "venus"
        user: mifos
        password: password
        authtype: basic
        fspId: payeefsp
      - name: "jupiter"
        user: mifos
        password: password
        authtype: basic
        fspId: payeefsp
      - name: "pluto"
        user: mifos
        password: password
        authtype: basic
        fspId: payeefsp

# Savings : S , Loan : L
accountPrefixes: "S,L"
