ams:
  local:
    interop:
      host: https://leopard.mifos.io:8443
    customer:
      host: https://leopard.mifos.io:8443
    account:
      host: https://leopard.mifos.io:8443
    auth:
      host: https://leopard.mifos.io:8443
    tenants:
      - name: tn05
        user: mifos
        password: password
        authtype: basic
        fspId: in03tn05
      - name: tn06
        user: mifos
        password: password
        authtype: basic
        fspId: in03tn06
