ams:
  local:
    interop:
      host: http://buffalo.mifos.io:2034
    customer:
      host: http://buffalo.mifos.io:2024
    account:
      host: http://buffalo.mifos.io:2027
    auth:
      host: http://buffalo.mifos.io:2021
    tenants:
      - name: tn01
        user: interopUser
        password: intop@d1
        authtype: oauth
        fspId: in01tn01
