ph-ee-engine:
  zeebe-cluster:
    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"

    elasticsearch:
      enabled: true
    kibana:
      enabled: false

  zeebe-operate:
    enabled: true

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE tn05;
        CREATE DATABASE tn06;
        GRANT ALL PRIVILEGES ON tn05.* TO 'mifos';
        GRANT ALL PRIVILEGES ON tn06.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,med"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "med"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-connector-channel.mifos.io"

  ph_ee_operations_app:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-operations.mifos.io"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "med"
    hostname: "med-operations.mifos.io"
    webhost: "med-operations-ui.mifos.io"

  ph_ee_identity:
    hostname: "med-identity.mifos.io"
