ph-ee-engine:
  zeebe-cluster:
    clusterSize: "3"
    partitionCount: "15"
    replicationFactor: "2"

    cpuThreadCount: "6"
    ioThreadCount: "2"

    #pvcStorageClassName: "fast-disks"
    JavaOpts: "-Xms32g -Xmx32g -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=25.0 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+PrintFlagsFinal"
    #JavaOpts: "-Xms32g -Xmx32g -XX:+UseParallelGC -XX:+PrintFlagsFinal"

    elasticsearch:
      enabled: true
    kibana:
      enabled: true

    resources: 
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 7820m
        memory: 48Gi

    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9600'
      prometheus.io/path: '/metrics'

    nodeSelector:
      agentpool: defaultv6

  zeebe-operate:
    enabled: true

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE tn01;
        CREATE DATABASE tn02;
        GRANT ALL PRIVILEGES ON tn01.* TO 'mifos';
        GRANT ALL PRIVILEGES ON tn02.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fincn,large"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "large"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-connector-channel.mifos.io"

  ph_ee_operations_app:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-operations.mifos.io"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "large"
    hostname: "large-operations.mifos.io"
    webhost: "large-operations-ui.mifos.io"

  ph_ee_identity:
    hostname: "large-identity.mifos.io"
