apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: in03tn05-ph-ee-connector-mojaloop-java
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: in03tn05.mifos.io
      http:
        paths:
        - backend:
            serviceName: ph-ee-connector-mojaloop-java
            servicePort: 80
